package model;
// Generated 17/10/2015 08:46:42 by Hibernate Tools 4.3.1

import java.sql.Time;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Funcion generated by hbm2java
 */
public class Funcion implements java.io.Serializable {

    private Integer id;
    private Pelicula pelicula;
    private Sala sala;
    private Date fecha;
    private Time hora;
    private Set reservas = new HashSet(0);

    public Funcion() {
    }

    public Funcion(Pelicula pelicula, Sala sala, Date fecha, Time hora, Set reservas) {
        this.pelicula = pelicula;
        this.sala = sala;
        this.fecha = fecha;
        this.hora = hora;
        this.reservas = reservas;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Pelicula getPelicula() {
        return this.pelicula;
    }

    public void setPelicula(Pelicula pelicula) {
        this.pelicula = pelicula;
    }

    public Sala getSala() {
        return this.sala;
    }

    public void setSala(Sala sala) {
        this.sala = sala;
    }

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fechaFuncion) {
        this.fecha = fechaFuncion;
    }

    public Date getHora() {
        return this.hora;
    }

    public void setHora(Time hora) {
        this.hora = hora;
    }

    public Set getReservas() {
        return this.reservas;
    }

    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }

}
