package model;
// Generated 17/10/2015 08:46:42 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Funcion generated by hbm2java
 */
public class Funcion implements java.io.Serializable {

    private Integer pkFuncion;
    private Pelicula pelicula;
    private Sala sala;
    private Date fechaFuncion;
    private Date horaFuncion;
    private Set reservas = new HashSet(0);

    public Funcion() {
    }

    public Funcion(Pelicula pelicula, Sala sala, Date fechaFuncion, Date horaFuncion, Set reservas) {
        this.pelicula = pelicula;
        this.sala = sala;
        this.fechaFuncion = fechaFuncion;
        this.horaFuncion = horaFuncion;
        this.reservas = reservas;
    }

    public Integer getPkFuncion() {
        return this.pkFuncion;
    }

    public void setPkFuncion(Integer pkFuncion) {
        this.pkFuncion = pkFuncion;
    }

    public Pelicula getPelicula() {
        return this.pelicula;
    }

    public void setPelicula(Pelicula pelicula) {
        this.pelicula = pelicula;
    }

    public Sala getSala() {
        return this.sala;
    }

    public void setSala(Sala sala) {
        this.sala = sala;
    }

    public Date getFechaFuncion() {
        return this.fechaFuncion;
    }

    public void setFechaFuncion(Date fechaFuncion) {
        this.fechaFuncion = fechaFuncion;
    }

    public Date getHoraFuncion() {
        return this.horaFuncion;
    }

    public void setHoraFuncion(Date horaFuncion) {
        this.horaFuncion = horaFuncion;
    }

    public Set getReservas() {
        return this.reservas;
    }

    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }

}
