package model;
// Generated 17/10/2015 08:46:42 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Pelicula generated by hbm2java
 */
public class Pelicula implements java.io.Serializable {

    private Integer id;
    private String titulo;
    private String director;
    private Double duracion;
    private String genero;
    private String imagen;
    private Set funcions = new HashSet(0);

    public Pelicula() {
    }

    public Pelicula(String titulo, String director, Double duracion, String genero, String imagen, Set funcions) {
        this.titulo = titulo;
        this.director = director;
        this.duracion = duracion;
        this.genero = genero;
        this.imagen = imagen;
        this.funcions = funcions;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTitulo() {
        return this.titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    public String getDirector() {
        return this.director;
    }

    public void setDirector(String director) {
        this.director = director;
    }

    public Double getDuracion() {
        return this.duracion;
    }

    public void setDuracion(Double duracion) {
        this.duracion = duracion;
    }

    public String getGenero() {
        return this.genero;
    }

    public void setGenero(String genero) {
        this.genero = genero;
    }

    public String getImagen() {
        return this.imagen;
    }

    public void setImagen(String imagen) {
        this.imagen = imagen;
    }

    public Set getFuncions() {
        return this.funcions;
    }

    public void setFuncions(Set funcions) {
        this.funcions = funcions;
    }

}
