package model;
// Generated 17/10/2015 08:46:42 by Hibernate Tools 4.3.1

/**
 * Reserva generated by hbm2java
 */
public class Reserva implements java.io.Serializable {

    private Integer id;
    private Funcion funcion;
    private Usuario usuario;

    public Reserva() {
    }

    public Reserva(Funcion funcion, Usuario usuario) {
        this.funcion = funcion;
        this.usuario = usuario;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Funcion getFuncion() {
        return this.funcion;
    }

    public void setFuncion(Funcion funcion) {
        this.funcion = funcion;
    }

    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

}
