package model;
// Generated 17/10/2015 08:46:42 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Sala generated by hbm2java
 */
public class Sala implements java.io.Serializable {

    private Integer pkSala;
    private Cine cine;
    private String nombre;
    private Integer filas;
    private Integer columnas;
    private Set funcions = new HashSet(0);

    public Sala() {
    }

    public Sala(Cine cine, String nombre, Integer filas, Integer columnas, Set funcions) {
        this.cine = cine;
        this.nombre = nombre;
        this.filas = filas;
        this.columnas = columnas;
        this.funcions = funcions;
    }

    public Integer getPkSala() {
        return this.pkSala;
    }

    public void setPkSala(Integer pkSala) {
        this.pkSala = pkSala;
    }

    public Cine getCine() {
        return this.cine;
    }

    public void setCine(Cine cine) {
        this.cine = cine;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Integer getFilas() {
        return this.filas;
    }

    public void setFilas(Integer filas) {
        this.filas = filas;
    }

    public Integer getColumnas() {
        return this.columnas;
    }

    public void setColumnas(Integer columnas) {
        this.columnas = columnas;
    }

    public Set getFuncions() {
        return this.funcions;
    }

    public void setFuncions(Set funcions) {
        this.funcions = funcions;
    }

}
